### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by samkitk** [Sameep1234/Database-Portfolio#1]
Database.java:19: error: cannot find symbol
 void add(DbObject d)throws IOException {
          ^
  symbol:   class DbObject
  location: class Database
Database.java:25: error: cannot find symbol
 void modify(DbObject d)throws IOException {
             ^
  symbol:   class DbObject
  location: class Database
Database.java:40: error: cannot find symbol
 boolean find(DbObject d)throws IOException {
              ^
  symbol:   class DbObject
  location: class Database
Database.java:55: error: cannot find symbol
 void printDb(DbObject d)throws IOException {
              ^
  symbol:   class DbObject
  location: class Database
Database.java:66: error: cannot find symbol
public void run(DbObject rec) throws IOException {
                ^
  symbol:   class DbObject
  location: class Database
Database.java:26: error: cannot find symbol
	 DbObject[] tmp = new DbObject[1];
	 ^
  symbol:   class DbObject
  location: class Database
Database.java:26: error: cannot find symbol
	 DbObject[] tmp = new DbObject[1];
	                      ^
  symbol:   class DbObject
  location: class Database
Database.java:42: error: cannot find symbol
	 DbObject[] tmp = new DbObject[1];
	 ^
  symbol:   class DbObject
  location: class Database
Database.java:42: error: cannot find symbol
	 DbObject[] tmp = new DbObject[1];
	                      ^
  symbol:   class DbObject
  location: class Database
Database.java:103: error: cannot find symbol
	portfolio.run(new Portfolio());
	                  ^
  symbol:   class Portfolio
  location: class Database
10 errors

**Comment by Sameep1234** [comment]
You must be opening/running it through the command prompt. Try opening and running it through an IDE like Netbeans. This works.
